//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A16_IzlozbaPasa_a
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgajivacnice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odgajivacnice()
        {
            this.Pas = new HashSet<Pas>();
        }
    
        public int OdgajivacniceId { get; set; }
        public string Naziv { get; set; }
        public string BrTelefona { get; set; }
        public string Email { get; set; }
        public string Adresa { get; set; }
        public string Drzava { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pas> Pas { get; set; }
    }
}
